# Render configuration file
# Docs: https://render.com/docs/yaml-spec
services:
  - type: web
    name: ayuda-animal-web
    env: python
    region: ohio
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi --chdir ./src/"
    plan: free
    numInstances: 1
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: []
    plan: free