services:
  - type: web
    name: ayuda-animal-web
    env: python
    region: fra
    pythonVersion: 3.13.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --chdir ./src/"
    plan: free
    numInstances: 1
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP_KEY
        value: "pon_aqui_una_clave_segura"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString
    healthCheckPath: /health
