services:
  - type: web
    name: ayuda-animal-web
    env: python
    region: fra
    pythonVersion: 3.10.12
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application --chdir ./src/"
    plan: free
    numInstances: 1
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP_KEY
        value: "pon_aqui_una_clave_segura"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString
    healthCheckPath: /health

databases:
  - name: postgresql-trapezoidal-42170
    region: fra
    plan: free
    ipAllowList: []
