"""Add adopted field to Cat

Revision ID: 3aee3d7894e2
Revises: 17df2bd0dc0b
Create Date: 2025-10-14 18:34:26.411075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aee3d7894e2'
down_revision = '17df2bd0dc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adopted', sa.Boolean(), nullable=False,server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('adopted')

    # ### end Alembic commands ###
