"""Add is_verified and verification_token to user

Revision ID: 99254f979b92
Revises: 3aee3d7894e2
Create Date: 2025-10-17 23:01:26.480660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99254f979b92'
down_revision = '3aee3d7894e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
